services:
  langfuse_dev:
    image: langfuse/langfuse:2
    environment:
      DATABASE_URL: ${LANGFUSE_DB_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      SALT: ${SALT}
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${LANGFUSE_DB}
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
